/**
 * `packages/shared/events.json` freeze tests (M1-3; spec §12.15-16; contracts.md
 * §2, §7.4 leg 1).
 *
 * events.json is GENERATED by contracts/script/codegen-abi.ts from forge
 * artifacts and cross-checked byte-for-byte against the spec-transcribed
 * fragments in src/abi/events.ts at generation time. These tests re-assert the
 * same seam from the consumer side: if they fail, either the artifact went
 * stale (rerun `bun contracts/script/codegen-abi.ts`) or the cross-service
 * contract changed — the latter requires robbed-architect ratification, not a
 * test update.
 */
import { describe, expect, it } from "bun:test";
import { readFileSync } from "node:fs";
import {
  graduatedEvent,
  tokenCreatedEvent,
  tradeEvent,
  transferEvent,
  v3CollectEvent,
  v3SwapEvent,
} from "../src/abi/events";

interface EventInput {
  name: string;
  type: string;
  indexed?: boolean;
}
interface EventFragment {
  type: string;
  name: string;
  inputs: EventInput[];
}
interface EventsJson {
  $generatedBy: string;
  contracts: Record<string, EventFragment[]>;
}

const eventsJson = JSON.parse(
  readFileSync(new URL("../events.json", import.meta.url), "utf8"),
) as EventsJson;

/** Same normalization the codegen uses: names + types + indexed flags + order. */
function normalize(ev: {
  name: string;
  inputs: readonly { name: string; type: string; indexed?: boolean }[];
}): string {
  return JSON.stringify({
    name: ev.name,
    inputs: ev.inputs.map((i) => ({ name: i.name, type: i.type, indexed: i.indexed === true })),
  });
}

function fragment(contract: string, name: string): EventFragment {
  const frag = eventsJson.contracts[contract]?.find((e) => e.name === name);
  if (!frag) throw new Error(`events.json missing ${contract}.${name}`);
  return frag;
}

describe("events.json — generated artifact shape", () => {
  it("is generated (never hand-written) and keyed by forge artifact", () => {
    expect(eventsJson.$generatedBy).toContain("contracts/script/codegen-abi.ts");
    expect(Object.keys(eventsJson.contracts).sort()).toEqual([
      "BondingCurve",
      "CurveFactory",
      "INonfungiblePositionManager",
      "IUniswapV3Pool",
      "LPFeeVault",
      "LaunchToken",
      "V3Migrator",
    ]);
    for (const frags of Object.values(eventsJson.contracts)) {
      for (const f of frags) expect(f.type).toBe("event");
    }
  });

  it("carries the M1-3 plan-item fields (metadataUri on TokenCreated, trader on Trade)", () => {
    expect(fragment("CurveFactory", "TokenCreated").inputs.map((i) => i.name)).toContain(
      "metadataUri",
    );
    expect(fragment("BondingCurve", "Trade").inputs.map((i) => i.name)).toContain("trader");
  });
});

describe("events.json ↔ events.ts — byte-for-byte (§12.15)", () => {
  const pairs: [string, string, Parameters<typeof normalize>[0]][] = [
    ["CurveFactory", "TokenCreated", tokenCreatedEvent],
    ["BondingCurve", "Trade", tradeEvent],
    ["V3Migrator", "Graduated", graduatedEvent],
    ["LaunchToken", "Transfer", transferEvent],
    ["IUniswapV3Pool", "Swap", v3SwapEvent],
    ["INonfungiblePositionManager", "Collect", v3CollectEvent],
  ];
  for (const [contract, name, specFragment] of pairs) {
    it(`${contract}.${name} matches the spec-transcribed fragment`, () => {
      expect(normalize(fragment(contract, name))).toBe(normalize(specFragment));
    });
  }
});

describe("events.json — protocol lifecycle/fee events (contracts.md §2)", () => {
  it("BondingCurve carries GraduationReady + FeesSwept (§12.25 pull-payment)", () => {
    expect(fragment("BondingCurve", "GraduationReady")).toBeDefined();
    const swept = fragment("BondingCurve", "FeesSwept");
    expect(swept.inputs.map((i) => i.name)).toEqual(["treasury", "amount"]);
  });

  it("V3Migrator carries PoolInitialized (§6.3.2 creation-time init)", () => {
    expect(fragment("V3Migrator", "PoolInitialized")).toBeDefined();
  });

  it("LPFeeVault carries FeesCollected (§6.3.4)", () => {
    expect(fragment("LPFeeVault", "FeesCollected").inputs.map((i) => i.name)).toEqual([
      "tokenId",
      "amount0",
      "amount1",
    ]);
  });
});
