/**
 * ─────────────────────────────────────────────────────────────────────────────
 *  GENERATED by contracts/script/codegen-addresses.ts — DO NOT HAND-EDIT.
 *  Source: contracts/deployments/<chainId>.json (emitted by script/Deploy.s.sol
 *  under `forge script … --broadcast`). Regenerate:
 *    bun contracts/script/codegen-addresses.ts
 *
 *  Deploy-time codegen (needs a broadcast) — the addresses seam of architecture.md
 *  §4: contracts-pipeline-owned, lives in packages/shared, consumed by the indexer
 *  config and web `shared/config/addresses.ts`. Every consumer selects ITS OWN
 *  chain via `getDeployment(chainId)`; local (31337 smoke) and live (4663) entries
 *  coexist here.
 * ─────────────────────────────────────────────────────────────────────────────
 */
import type { Address } from "viem";

export type DeploymentMode = "local" | "live";

/** The six-contract robbed topology + treasury for one chain (spec §6, §6.6). */
export interface Deployment {
  chainId: number;
  mode: DeploymentMode;
  deployedAt: number;
  /** The four singletons (§6) + the treasury Safe (§6.6). */
  robbed: {
    curveFactory: Address;
    router: Address;
    v3Migrator: Address;
    lpFeeVault: Address;
    treasury: Address;
  };
  /** Canonical externals wired at deploy (§12.28): WETH + the four Uniswap V3 addrs. */
  external: {
    weth: Address;
    v3Factory: Address;
    positionManager: Address;
    swapRouter02: Address;
    quoterV2: Address;
  };
  /** The deploy-time canary launch (§7.2 step 6) — informational; not a user token. */
  canary: { token: Address; curve: Address };
}

/** Every recorded deployment, keyed by chain id (string). @generated */
export const ROBBED_DEPLOYMENTS = {
  "31337": {
    chainId: 31337,
    mode: "local",
    deployedAt: 1783686794,
    robbed: {
      curveFactory: "0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9",
      router: "0x0165878A594ca255338adfa4d48449f69242Eb8F",
      v3Migrator: "0x5FC8d32690cc91D4c39d9d3abcBD16989F875707",
      lpFeeVault: "0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9",
      treasury: "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266",
    },
    external: {
      weth: "0x5FbDB2315678afecb367f032d93F642f64180aa3",
      v3Factory: "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512",
      positionManager: "0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0",
      swapRouter02: "0xCaf681a66D020601342297493863E78C959E5cb2",
      quoterV2: "0x33e885eD0Ec9bF04EcfB19341582aADCb4c8A9E7",
    },
    canary: {
      token: "0x856e4424f806D16E8CBC702B3c0F2ede5468eae5",
      curve: "0x8d38Ce174fBA60425b0A1d4d8a343010338576c8",
    },
  },
} as const satisfies Record<string, Deployment>;

/** Chain ids with a recorded deployment. @generated */
export type DeployedChainId = keyof typeof ROBBED_DEPLOYMENTS;

/**
 * Resolve the deployment for `chainId`, or `undefined` when none has been
 * broadcast+codegen'd for that chain yet (consumers then fail loud — see web
 * `requireAddress`). Never invents an address.
 */
export function getDeployment(chainId: number): Deployment | undefined {
  return (ROBBED_DEPLOYMENTS as Record<string, Deployment>)[String(chainId)];
}
