/**
 * ─────────────────────────────────────────────────────────────────────────────
 *  GENERATED by contracts/script/codegen-addresses.ts — DO NOT HAND-EDIT.
 *  Source: contracts/deployments/<chainId>.json (emitted by script/Deploy.s.sol
 *  under `forge script … --broadcast`). Regenerate:
 *    bun contracts/script/codegen-addresses.ts
 *
 *  Deploy-time codegen (needs a broadcast) — the addresses seam of architecture.md
 * : contracts-pipeline-owned, lives in packages/shared, consumed by the indexer
 *  config and web `shared/config/addresses.ts`. Every consumer selects ITS OWN
 *  chain via `getDeployment(chainId)`; local (31337 smoke), testnet (46630) and
 *  live (4663) entries coexist here.
 * ─────────────────────────────────────────────────────────────────────────────
 */
import type { Address } from "viem";

/**
 * A 4663 `fork` is a mainnet-FORK pipeline run (anvil --fork-url): same chainid as
 * `live` but deliberately NOT live so a fork can never masquerade as a real mainnet
 * deployment. Consumers that require a canonical mainnet entry MUST assert
 * `mode === "live"`; the indexer's chain-identity gate does exactly this.
 */
export type DeploymentMode = "local" | "testnet" | "live" | "fork";

/** The six-contract robbed topology + treasury for one chain. */
export interface Deployment {
  chainId: number;
  mode: DeploymentMode;
  deployedAt: number;
  /** The four singletons + the treasury Safe. */
  robbed: {
    curveFactory: Address;
    router: Address;
    v3Migrator: Address;
    lpFeeVault: Address;
    treasury: Address;
    /**
     * The Phase-2 pull-payment CreatorVault. OPTIONAL +
     * additive: absent on every v1 deployment (no vault exists until a
     * creator-fee factory is deployed), so the existing entries below stay valid
     * against this shape. Once a creator-fee deploy artifact carries it, codegen
     * emits `robbed.creatorVault` and consumers (indexer CreatorVault source,
     * web claim widget) get it typed. CODEGEN-LOCKSTEP (report): the pipeline's
     * `contracts/script/codegen-addresses.ts` — `Artifact`/`ADDR_KEYS` + the
     * `robbed:` emit block + this interface template — must add `creatorVault`
     * (optional) so a regen doesn't drop this field; robbed-contracts owns that.
     */
    creatorVault?: Address;
  };
  /** Canonical externals wired at deploy : WETH + the four Uniswap V3 addrs. */
  external: {
    weth: Address;
    v3Factory: Address;
    positionManager: Address;
    swapRouter02: Address;
    quoterV2: Address;
  };
  /** The deploy-time canary launch (step 6) — informational; not a user token. */
  canary: { token: Address; curve: Address };
}

/** Every recorded deployment, keyed by chain id (string). @generated */
export const ROBBED_DEPLOYMENTS = {
  "4663": {
    chainId: 4663,
    mode: "fork",
    deployedAt: 1784120861,
    robbed: {
      curveFactory: "0x49fd2BE640DB2910c2fAb69bB8531Ab6E76127ff",
      router: "0xf953b3A269d80e3eB0F2947630Da976B896A8C5b",
      v3Migrator: "0xA4899D35897033b927acFCf422bc745916139776",
      lpFeeVault: "0x86A2EE8FAf9A840F7a2c64CA3d51209F9A02081D",
      treasury: "0x70997970C51812dc3A010C7d01b50e0d17dc79C8",
      creatorVault: "0x4631BCAbD6dF18D94796344963cB60d44a4136b6",
    },
    external: {
      weth: "0x0Bd7D308f8E1639FAb988df18A8011f41EAcAD73",
      v3Factory: "0x1f7d7550B1b028f7571E69A784071F0205FD2EfA",
      positionManager: "0x73991a25C818Bf1f1128dEAaB1492D45638DE0D3",
      swapRouter02: "0xCaf681a66D020601342297493863E78C959E5cb2",
      quoterV2: "0x33e885eD0Ec9bF04EcfB19341582aADCb4c8A9E7",
    },
    canary: {
      token: "0xD781C44726058d2971B58408c492192877FAAC17",
      curve: "0x31C425D38753A2F04cb3B7924C33CfF7EC8288fB",
    },
  },
  "31337": {
    chainId: 31337,
    mode: "local",
    deployedAt: 1783686794,
    robbed: {
      curveFactory: "0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9",
      router: "0x0165878A594ca255338adfa4d48449f69242Eb8F",
      v3Migrator: "0x5FC8d32690cc91D4c39d9d3abcBD16989F875707",
      lpFeeVault: "0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9",
      treasury: "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266",
    },
    external: {
      weth: "0x5FbDB2315678afecb367f032d93F642f64180aa3",
      v3Factory: "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512",
      positionManager: "0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0",
      swapRouter02: "0xCaf681a66D020601342297493863E78C959E5cb2",
      quoterV2: "0x33e885eD0Ec9bF04EcfB19341582aADCb4c8A9E7",
    },
    canary: {
      token: "0x856e4424f806D16E8CBC702B3c0F2ede5468eae5",
      curve: "0x8d38Ce174fBA60425b0A1d4d8a343010338576c8",
    },
  },
  "46630": {
    chainId: 46630,
    mode: "testnet",
    deployedAt: 1784121530,
    robbed: {
      curveFactory: "0x5Bf96c640793a3DDB1181b34f6E501771Eb7A79a",
      router: "0x5C5A4Abd34f8A6484b8eF4D3a587B0bB2e22f1e8",
      v3Migrator: "0x571102fa88AEa1951187C0C6F08CE6c24886f17c",
      lpFeeVault: "0xF8786BdB1a579362e0CA3A5883886A22b091faD4",
      treasury: "0x9b318513D626b25C39Ae3416F23EAF5566998805",
      creatorVault: "0x407013930670289ad7a6dAdFfBEc5dcBF35B6CcF",
    },
    external: {
      weth: "0x7943e237c7F95DA44E0301572D358911207852Fa",
      v3Factory: "0xdf9e3D6ffaC4513dD7b053212bbECcbCD15ec932",
      positionManager: "0xFFe6CFc4f759b65f9B62c9D05A9E21a78cE93e12",
      swapRouter02: "0xb79cB26e90EBBD9bC02c75267c9a86dBa1AFedB7",
      quoterV2: "0xDDcBe4989C8171F721c5e683C9C6339B59718213",
    },
    canary: {
      token: "0xC9aC053A269790A653D143f4AD7168CD2fd787ad",
      curve: "0xB6237Af2a89D460761299269927c1805366CcB48",
    },
  },
} as const satisfies Record<string, Deployment>;

/** Chain ids with a recorded deployment. @generated */
export type DeployedChainId = keyof typeof ROBBED_DEPLOYMENTS;

/**
 * Resolve the deployment for `chainId`, or `undefined` when none has been
 * broadcast+codegen'd for that chain yet (consumers then fail loud — see web
 * `requireAddress`). Never invents an address.
 */
export function getDeployment(chainId: number): Deployment | undefined {
  return (ROBBED_DEPLOYMENTS as Record<string, Deployment>)[String(chainId)];
}
