/**
 * ─────────────────────────────────────────────────────────────────────────────
 *  GENERATED by contracts/script/codegen-addresses.ts — DO NOT HAND-EDIT.
 *  Source: contracts/deployments/<chainId>.json (emitted by script/Deploy.s.sol
 *  under `forge script … --broadcast`). Regenerate:
 *    bun contracts/script/codegen-addresses.ts
 *
 *  Deploy-time codegen (needs a broadcast) — the addresses seam of architecture.md
 *  §4: contracts-pipeline-owned, lives in packages/shared, consumed by the indexer
 *  config and web `shared/config/addresses.ts`. Every consumer selects ITS OWN
 *  chain via `getDeployment(chainId)`; local (31337 smoke), testnet (46630) and
 *  live (4663) entries coexist here.
 * ─────────────────────────────────────────────────────────────────────────────
 */
import type { Address } from "viem";

/**
 * A 4663 `fork` is a mainnet-FORK pipeline run (anvil --fork-url): same chainid as
 * `live` but deliberately NOT live so a fork can never masquerade as a real mainnet
 * deployment (§12.55). Consumers that require a canonical mainnet entry MUST assert
 * `mode === "live"`; the indexer's chain-identity gate does exactly this.
 */
export type DeploymentMode = "local" | "testnet" | "live" | "fork";

/** The six-contract robbed topology + treasury for one chain (spec §6, §6.6). */
export interface Deployment {
  chainId: number;
  mode: DeploymentMode;
  deployedAt: number;
  /** The four singletons (§6) + the treasury Safe (§6.6). */
  robbed: {
    curveFactory: Address;
    router: Address;
    v3Migrator: Address;
    lpFeeVault: Address;
    treasury: Address;
    /**
     * The Phase-2 pull-payment CreatorVault (spec §7 / §12.63). OPTIONAL +
     * additive: absent on every v1 deployment (no vault exists until a
     * creator-fee factory is deployed), so the existing entries below stay valid
     * against this shape. Once a creator-fee deploy artifact carries it, codegen
     * emits `robbed.creatorVault` and consumers (indexer CreatorVault source,
     * web claim widget) get it typed. CODEGEN-LOCKSTEP (report): the pipeline's
     * `contracts/script/codegen-addresses.ts` — `Artifact`/`ADDR_KEYS` + the
     * `robbed:` emit block + this interface template — must add `creatorVault`
     * (optional) so a regen doesn't drop this field; robbed-contracts owns that.
     */
    creatorVault?: Address;
  };
  /** Canonical externals wired at deploy (§12.28): WETH + the four Uniswap V3 addrs. */
  external: {
    weth: Address;
    v3Factory: Address;
    positionManager: Address;
    swapRouter02: Address;
    quoterV2: Address;
  };
  /** The deploy-time canary launch (§7.2 step 6) — informational; not a user token. */
  canary: { token: Address; curve: Address };
}

/** Every recorded deployment, keyed by chain id (string). @generated */
export const ROBBED_DEPLOYMENTS = {
  "4663": {
    chainId: 4663,
    mode: "fork",
    deployedAt: 1783887345,
    robbed: {
      curveFactory: "0xE6E340D132b5f46d1e472DebcD681B2aBc16e57E",
      router: "0x84eA74d481Ee0A5332c457a4d796187F6Ba67fEB",
      v3Migrator: "0xc3e53F4d16Ae77Db1c982e75a937B9f60FE63690",
      lpFeeVault: "0x67d269191c92Caf3cD7723F116c85e6E9bf55933",
      treasury: "0x70997970C51812dc3A010C7d01b50e0d17dc79C8",
    },
    external: {
      weth: "0x0Bd7D308f8E1639FAb988df18A8011f41EAcAD73",
      v3Factory: "0x1f7d7550B1b028f7571E69A784071F0205FD2EfA",
      positionManager: "0x73991a25C818Bf1f1128dEAaB1492D45638DE0D3",
      swapRouter02: "0xCaf681a66D020601342297493863E78C959E5cb2",
      quoterV2: "0x33e885eD0Ec9bF04EcfB19341582aADCb4c8A9E7",
    },
    canary: {
      token: "0x4F57F9239eFCBf43e5920f579D03B3849C588396",
      curve: "0x0B40C66BD7BA81485527C41B3730a95f113ED89E",
    },
  },
  "31337": {
    chainId: 31337,
    mode: "local",
    deployedAt: 1783686794,
    robbed: {
      curveFactory: "0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9",
      router: "0x0165878A594ca255338adfa4d48449f69242Eb8F",
      v3Migrator: "0x5FC8d32690cc91D4c39d9d3abcBD16989F875707",
      lpFeeVault: "0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9",
      treasury: "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266",
    },
    external: {
      weth: "0x5FbDB2315678afecb367f032d93F642f64180aa3",
      v3Factory: "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512",
      positionManager: "0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0",
      swapRouter02: "0xCaf681a66D020601342297493863E78C959E5cb2",
      quoterV2: "0x33e885eD0Ec9bF04EcfB19341582aADCb4c8A9E7",
    },
    canary: {
      token: "0x856e4424f806D16E8CBC702B3c0F2ede5468eae5",
      curve: "0x8d38Ce174fBA60425b0A1d4d8a343010338576c8",
    },
  },
  "46630": {
    chainId: 46630,
    mode: "testnet",
    deployedAt: 1783899730,
    robbed: {
      curveFactory: "0x7355BD34Bc12002F2bDc79A4791463d7d6D2529a",
      router: "0x6480534B6992419535554451BBDe79B898011BA8",
      v3Migrator: "0x4Bc86C3fdBABbFEF82094A772bA0194e980A5567",
      lpFeeVault: "0x3B4dD3B5741EDcE6e08CE2BcbE3106035A3E8e75",
      treasury: "0x4ae5b5Ae7D2edd7A2d43054246D6aaAcAAFC1000",
      creatorVault: "0xE032467128A87e353b69AeDf8e97B0AA9d528eBB",
    },
    external: {
      weth: "0x7943e237c7F95DA44E0301572D358911207852Fa",
      v3Factory: "0xdf9e3D6ffaC4513dD7b053212bbECcbCD15ec932",
      positionManager: "0xFFe6CFc4f759b65f9B62c9D05A9E21a78cE93e12",
      swapRouter02: "0xb79cB26e90EBBD9bC02c75267c9a86dBa1AFedB7",
      quoterV2: "0xDDcBe4989C8171F721c5e683C9C6339B59718213",
    },
    canary: {
      token: "0xFF6e101f6Ddf202F513A8f7255c61c3BAd806AB2",
      curve: "0x7cd37Dc905C89D970F2E6952D721F49cba284aC7",
    },
  },
} as const satisfies Record<string, Deployment>;

/** Chain ids with a recorded deployment. @generated */
export type DeployedChainId = keyof typeof ROBBED_DEPLOYMENTS;

/**
 * Resolve the deployment for `chainId`, or `undefined` when none has been
 * broadcast+codegen'd for that chain yet (consumers then fail loud — see web
 * `requireAddress`). Never invents an address.
 */
export function getDeployment(chainId: number): Deployment | undefined {
  return (ROBBED_DEPLOYMENTS as Record<string, Deployment>)[String(chainId)];
}
